if (!require('randomForest')){install.packages('randomForest')}; library(randomForest)
if (!require('datasets')){install.packages('datasets')}; library(datasets)
if (!require('caret')){install.packages('caret')}; library(caret)
if (!require('ROCR')){install.packages('ROCR')}; library(ROCR)
if (!require('magrittr')){install.packages('magrittr')}; library(magrittr)
if (!require('shiny')){install.packages('shiny')}; library(shiny)
if (!require('markdown')){install.packages('markdown')}; library(markdown)
if (!require('shinyWidgets')){install.packages('shinyWidgets')}; library(shinyWidgets)
if (!require('DT')){install.packages('DT')}; library(DT)
if (!require('kernlab')){install.packages('kernlab')}; library(kernlab)
if (!require('klaR')){install.packages('klaR')}; library(klaR)
if (!require('tidyverse')){install.packages('tidyverse')}; library(tidyverse)
if (!require('Amelia')){install.packages('Amelia')}; library(Amelia)
if (!require('mlbench')){install.packages('mlbench')}; library(mlbench)
if (!require('dplyr')){install.packages('dplyr')}; library(dplyr)
if (!require('ROCR')){install.packages('ROCR')}; library(ROCR)
if (!require('pROC')){install.packages('pROC')}; library(pROC)
if (!require('MLmetrics')){install.packages('MLmetrics')}; library(MLmetrics)


